apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot
  namespace: dev
  labels:
    app: polybot
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polybot
      environment: dev
  template:
    metadata:
      labels:
        app: polybot
        environment: dev
    spec:
      containers:
      - name: polybot
        image: maisash/polybot-dev
        ports:
        - containerPort: 8443
          name: webhook
        env:
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: polybot-secrets
              key: telegram-token
        - name: TELEGRAM_APP_URL
          value: "https://maisadev.fursa.click"
        - name: YOLO_SERVICE_URL
          value: "http://yolo-service:8080"
        - name: ENVIRONMENT
          value: "dev"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: polybot-service
  namespace: dev
  labels:
    app: polybot
    environment: dev
spec:
  selector:
    app: polybot
    environment: dev
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: webhook
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: polybot-secrets
  namespace: dev
type: Opaque
data:
  telegram-token: NzcwOTE0NTMyNDpBQUc5WmFNMXd0Wi1LLUhEbFlyVnotOHBwNFFVRDlORXhzaw==
