name: Deploy Nginx Container to dev

on:
  push:
    paths:
      - "nginx-config/polybot-dev.conf"
      - "scripts/deploy_nginx_container.sh"
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Create target dirs
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_DEV_HOST }} << 'EOF'
          mkdir -p /home/ubuntu/conf.d
          mkdir -p /home/ubuntu/certs
        EOF

    - name: Copy config and script
      run: |
        scp -i key.pem -o StrictHostKeyChecking=no \
          nginx-config/polybot-dev.conf \
          ubuntu@${{ secrets.EC2_DEV_HOST }}:/home/ubuntu/conf.d/default.conf

        scp -i key.pem -o StrictHostKeyChecking=no \
          scripts/deploy_nginx_container.sh \
          ubuntu@${{ secrets.EC2_DEV_HOST }}:/home/ubuntu/

    - name: Run deploy script
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_DEV_HOST }} << 'EOF'
          chmod +x /home/ubuntu/deploy_nginx_container.sh
          /home/ubuntu/deploy_nginx_container.sh
        EOF
