name: Nginx Dev Deploy

on:
  push:
    paths:
      - "nginx-config/polybot-dev.conf"
      - "scripts/deploy_nginx.sh"
    branches:
      - dev
  workflow_dispatch:

env:
  REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_DEV_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat > ~/.ssh/config << EOF
          Host ec2
              HostName $EC2_HOST
              User $EC2_USERNAME
              IdentityFile ~/.ssh/private_key
              StrictHostKeyChecking no
          EOF

      - name: Ensure target directories exist on EC2
        run: |
          ssh ec2 << 'EOF'
            mkdir -p /home/ubuntu/conf.d
            mkdir -p /home/ubuntu/certs
          EOF

      - name: Copy Nginx config and deploy script to EC2
        run: |
          scp -i ~/.ssh/private_key -o StrictHostKeyChecking=no \
            nginx-config/polybot-dev.conf \
            ec2:/home/ubuntu/conf.d/

          scp -i ~/.ssh/private_key -o StrictHostKeyChecking=no \
            scripts/deploy_nginx.sh \
            ec2:/home/ubuntu/

      - name: Run deploy script on EC2
        run: |
          ssh ec2 << 'EOF'
            chmod +x /home/ubuntu/deploy_nginx.sh
            /home/ubuntu/deploy_nginx.sh
          EOF
