name: Refresh K8s Join Token

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  workflow_dispatch:       # allow manual trigger too

jobs:
  refresh-token:
    runs-on: ubuntu-latest

    # Add AWS environment variables
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug - Check AWS credentials and connectivity
      run: |
        echo "=== AWS Environment Check ==="
        echo "AWS_REGION: $AWS_REGION"
        echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:0:10}..." # Show first 10 chars only
        echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:0:10}..." # Show first 10 chars only
        
        echo "=== AWS CLI Version ==="
        aws --version
        
        echo "=== AWS Identity Check ==="
        aws sts get-caller-identity
        
        echo "=== AWS Region Check ==="
        aws configure get region
        
        echo "=== Test Secrets Manager Access ==="
        aws secretsmanager list-secrets --region $AWS_REGION --max-items 5
        
        echo "=== Check if K8S_JOIN_COMMAND secret exists ==="
        aws secretsmanager describe-secret --secret-id K8S_JOIN_COMMAND --region $AWS_REGION || echo "Secret does not exist yet"

    - name: Debug - Check SSH connectivity
      run: |
        echo "=== SSH Connection Test ==="
        echo "Control Plane IP: ${{ secrets.CONTROL_PLANE_IP }}"
        # Test if the host is reachable
        ping -c 3 ${{ secrets.CONTROL_PLANE_IP }} || echo "Host not reachable via ping"
        
        # Test SSH port
        timeout 10 nc -zv ${{ secrets.CONTROL_PLANE_IP }} 22 || echo "SSH port not accessible"

    - name: Refresh join token via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.CONTROL_PLANE_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION
        script: |
          echo "=== Starting join token refresh process ==="
          
          # Set AWS environment variables for the remote session
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export AWS_REGION=$AWS_REGION
          
          echo "=== Remote Environment Check ==="
          echo "AWS_REGION: $AWS_REGION"
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"
          
          # Check if kubectl is working
          echo "=== Kubernetes Cluster Check ==="
          kubectl cluster-info || echo "kubectl not working or cluster not initialized"
          kubectl get nodes || echo "Cannot get nodes"
          
          # Check if kubeadm is available
          echo "=== Kubeadm Check ==="
          which kubeadm || echo "kubeadm not found"
          kubeadm version || echo "kubeadm version failed"
          
          # Check existing tokens
          echo "=== Current Tokens ==="
          kubeadm token list || echo "Cannot list tokens"
          
          # Download and execute the refresh script
          echo "=== Downloading refresh script ==="
          curl -O https://raw.githubusercontent.com/${{ github.repository }}/main/scripts/refresh-k8s-join-token.sh
          
          echo "=== Script content ==="
          cat refresh-k8s-join-token.sh
          
          echo "=== Making script executable ==="
          chmod +x refresh-k8s-join-token.sh
          
          echo "=== Executing refresh script ==="
          ./refresh-k8s-join-token.sh
          
          echo "=== Verifying secret was updated ==="
          aws secretsmanager get-secret-value --secret-id K8S_JOIN_COMMAND --region $AWS_REGION --query SecretString --output text | head -20

    - name: Debug - Verify secret update
      run: |
        echo "=== Final Verification ==="
        echo "Checking if secret was updated successfully..."
        
        # Get the secret value and show some info about it
        SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id K8S_JOIN_COMMAND --region $AWS_REGION --query SecretString --output text)
        
        echo "Secret length: ${#SECRET_VALUE}"
        echo "Secret starts with: ${SECRET_VALUE:0:50}..."
        
        # Verify it looks like a valid kubeadm join command
        if [[ $SECRET_VALUE == *"kubeadm join"* ]]; then
          echo "✅ Secret contains valid kubeadm join command"
        else
          echo "❌ Secret does not contain valid kubeadm join command"
          echo "Full secret (first 200 chars): ${SECRET_VALUE:0:200}"
        fi

    - name: Debug - Test worker node connection (Optional)
      if: always()  # Run even if previous steps failed
      run: |
        echo "=== Worker Node Test ==="
        echo "Testing if worker nodes can retrieve the join command..."
        
        # Simulate what a worker node would do
        JOIN_COMMAND=$(aws secretsmanager get-secret-value \
          --region $AWS_REGION \
          --secret-id K8S_JOIN_COMMAND \
          --query SecretString \
          --output text)
        
        echo "Retrieved join command: ${JOIN_COMMAND:0:100}..."
        
        # Basic validation
        if [[ $JOIN_COMMAND == *"sudo kubeadm join"* ]]; then
          echo "✅ Join command format is correct"
        else
          echo "❌ Join command format is incorrect"
        fi